### PR TITLE
Make Conn fully net.Conn compatible

### PR DESCRIPTION
**Pull request by at-wat**
* Implement `Read/WriteDeadline`
* Return remained data on `Read` after `Close`
* Move network related internal packages under `internal/net/`
* Test using `nettest.TestConn`

### Reference issue
related: #148

### CODE REVIEW

**Comment by at-wat** [comment]
passed `nettest.TestConn`

**Comment by at-wat** [comment]
I set branch of the dtls module to this at https://github.com/pion/webrtc/pull/1004. All tests seem working correctly.

**Comment by daenney** [comment]
Ah excellent. :shipit:

**Comment by at-wat** [comment]
rebased

**Pull request merged**
