### PR TITLE
Upgrade pion/transport dependency to v0.13.0

### PR DESCRIPTION
**Pull request by daenney**
This fixes a deadlock in the transport.

### CODE REVIEW

**Comment by daenney** [comment]
@jkralik @at-wat

**Comment by daenney** [comment]
Something is profoundly broken with codecov. There's no way that updated a dependency results in a 10% decrease of code coverage in this library.

**Comment by jkralik** [comment]
Thx for the quick reaction.

**Comment by daenney** [comment]
Np! If someone can approve the PR then I'll do a release.

**Review by jkralik — APPROVED** [review]

**Pull request merged**
