### PR TITLE
Add TLS_PSK_WITH_AES_128_GCM_SHA256

### LINKED ISSUE #77: Support TLS_PSK_WITH_AES_128_GCM_SHA256 (Philips Hue Entertainment API)
In the same spirit as #45, I'd like to add support for `TLS_PSK_WITH_AES_128_GCM_SHA256` which is what Philips uses for the new Hue Entertainment API.

Given we already have PSK support thanks to @Sean-Der's efforts on #45, #76 and we already have AES_128_GCM_SHA256 I suspect this should be relatively straightforward.

I'll take a look at this in the coming weeks, just wanted to file an issue here so it's tracked somewhere.

### PR DESCRIPTION
**Pull request by daenney**
Fixes #77

### CODE REVIEW

**Comment by daenney** [comment]
I'm a bit puzzled. The e2e test would suggest this is all it takes. But it can't be that simple, can it?

**Comment by Sean-Der** [comment]
Looking it over I do think it should be that simple! That is really awesome.

If you run the client/server against OpenSSL does it all work?

We should probably explicitly name CipherSuites in the README.md 

Now that we do the ECDH and PSK it is confusing/misleading. We should list everything we support explicitly

**Comment by daenney** [comment]
> We should probably explicitly name CipherSuites in the README.md
> Now that we do the ECDH and PSK it is confusing/misleading. We should list everything we support explicitly

Agreed. I've added the README changes to this PR

**Comment by daenney** [comment]
@Sean-Der I updated the commit message linter. It keeps tripping up on a pure empty 2nd line, b/c at that point the character count is 0, not 1. I changed it to match on word instead which solves the problem. I've added a more complete description in the commit.

**Comment by daenney** [comment]
It's getting a bit late here, I'll try a ping-pong with OpenSSL tomorrow. If it works I'll proceed with merging this.

**Comment by daenney** [comment]
I'm a bit flabbergasted but everything does appear to work:

```diff
diff --git a/examples/dial-psk/main.go b/examples/dial-psk/main.go
index 6644f0b..82f8fb4 100644
--- a/examples/dial-psk/main.go
+++ b/examples/dial-psk/main.go
@@ -23,7 +23,7 @@ func main() {
 			return []byte{0xAB, 0xC1, 0x23}, nil
 		},
 		PSKIdentityHint: []byte("Pion DTLS Server"),
-		CipherSuites:    []dtls.CipherSuiteID{dtls.TLS_PSK_WITH_AES_128_CCM8},
+		CipherSuites:    []dtls.CipherSuiteID{dtls.TLS_PSK_WITH_AES_128_GCM_SHA256},
 	}
 
 	// Connect to a DTLS server
diff --git a/examples/listen-psk/main.go b/examples/listen-psk/main.go
index 059951f..83a89b0 100644
--- a/examples/listen-psk/main.go
+++ b/examples/listen-psk/main.go
@@ -23,7 +23,7 @@ func main() {
 			return []byte{0xAB, 0xC1, 0x23}, nil
 		},
 		PSKIdentityHint: []byte("Pion DTLS Client"),
-		CipherSuites:    []dtls.CipherSuiteID{dtls.TLS_PSK_WITH_AES_128_CCM8},
+		CipherSuites:    []dtls.CipherSuiteID{dtls.TLS_PSK_WITH_AES_128_GCM_SHA256},
 	}
 
 	// Connect to a DTLS server
```

```
$ openssl s_server -dtls1_2 -accept 4444 -nocert -psk abc123 -cipher PSK-AES128-GCM-SHA256
Using default temp DH parameters
ACCEPT
PSK warning: client identity not what we expected (got 'Pion DTLS Server' expected 'Client_identity')
-----BEGIN SSL SESSION PARAMETERS-----
MIGKAgEBAgMA/v0EAgCoBCAPkxkxGG6R/yRmEk/G4nm8txwIb98fpmgdncxDVAsl
CQQwj/+Q6jiYVfDnJrMCbNXF229knnzRA90zrerwFuAWbDT4dZu2wDXjGj18ZXu8
Xe9NoQYCBF0dP+yiBAICHCCkBgQEAQAAAKgSBBBQaW9uIERUTFMgU2VydmVy
-----END SSL SESSION PARAMETERS-----
Shared ciphers:PSK-AES128-GCM-SHA256
Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512
Shared Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512
---
No server certificate CA names sent
CIPHER is PSK-AES128-GCM-SHA256
Secure Renegotiation IS NOT supported
```

```
$ openssl s_client -dtls1_2 -connect 127.0.0.1:4444 -psk abc123 -cipher PSK-AES128-GCM-SHA256
CONNECTED(00000003)
Can't use SSL_get_servername
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 304 bytes and written 407 bytes
Verification: OK
New, TLSv1.2, Cipher is PSK-AES128-GCM-SHA256
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : DTLSv1.2
    Cipher    : PSK-AES128-GCM-SHA256
    Session-ID:
    Session-ID-ctx:
    Master-Key: 5B2071BFF70A8089C337B845449DC38AFF771584AF23C6D60AC6038B9D4B6BBC5384CB6EE8B81C6601FA82C55D17FFBE
    PSK identity: Client_identity
    PSK identity hint: Pion DTLS Client
    SRP username: None
    Start Time: 1562198073
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```

**Comment by Sean-Der** [comment]
@daenney That is awesome. I am feel really good about with how we designed everything :) doing things the right way paid off!

I think we need to some minor refactoring `/` feels really bloated to me. Would love too see a bunch of small `internal` packages though @igolaizola @daenney agree/disagree? I can cut the PRs!

**Comment by Sean-Der** [comment]
@daenney not a big deal, but would the lint pass if you added `Closes #77` to the `README` commit?

It would be nice not to update the lint, since we share them across all Pion repos. We need to write some sort of script that ensures they all stay in sync. If not possible totally understand!

**Comment by daenney** [comment]
@Sean-Der Yeah, that works too, hadn't considered that. Updated both commits now. I'll see about fixing this across repos. Now I'm just adding things to my commit in order to make the linter happy, that seems counter-productive.

**Comment by daenney** [comment]
> I think we need to some minor refactoring / feels really bloated to me. Would love too see a bunch of small internal packages though @igolaizola @daenney agree/disagree? I can cut the PRs!

I'm not sure what you're getting at here? Related to this PR or just in general?

**Pull request merged**
