### PR TITLE
Update CI configs to v0.1.0

### PR DESCRIPTION
**Pull request by pionbot**
Update lint scripts and CI configs.

### CODE REVIEW

**Comment by at-wat** [comment]
```
$ bash .github/lint-filename.sh
cipher_suite_tls_ecdhe_rsa_with_aes_256_cbc_sha.go is not a valid filename for Go code, only alpha and underscores are supported
The command "bash .github/lint-filename.sh" exited with 1.
```
https://github.com/pion/.goassets/issues/7

**Comment by at-wat** [comment]
```
verifying golang.org/x/crypto@v0.0.0-20191227163750-53104e6ec876: golang.org/x/crypto@v0.0.0-20191227163750-53104e6ec876: open /go/pkg/sumdb/sum.golang.org/latest: no such file or directory
```

**Comment by daenney** [comment]
Can you drop f8dee74bc8b71d563808e99525a028bfc0d2afdd from this, since it's now in #175?

**Comment by at-wat** [comment]
@daenney I'll close this PR as the lint script should be fixed (https://github.com/pion/.goassets/pull/8).

**Pull request closed without merging**
