### PR TITLE
Add support for ed25519 keys

### PR DESCRIPTION
**Pull request by rumpelsepp**
see discussion here:
https://github.com/pion/dtls/issues/133

### CODE REVIEW

**Comment by rumpelsepp** [comment]
tests added

**Comment by rumpelsepp** [comment]
The tests fail due to false positives… How to proceed?

**Comment by rumpelsepp** [comment]
I also added a helper method to remove the code duplication. `SelfSign()` can be used to create self signed certs from both ecdsa and ed25519 keys.

**Comment by rumpelsepp** [comment]
The linter *is* really annoying. Here you are. I disabled the security check on the random number generation, since it is obviously a false positive. There is only `crypto/rand` imported…

**Comment by Sean-Der** [comment]
Merged, no this was perfect thank you so much @rumpelsepp!

Would you be interested in joining the Pion org and helping out with `pion/dtls`? Always looking for people who are interested :)

I love the refactor PRs, and changes like that would be great (anything goes IMO as long as it doesn't change the public API or break tests!)

**Comment by rumpelsepp** [comment]
> Would you be interested in joining the Pion org and helping out with pion/dtls? Always looking for people who are interested :)

Sure! I can try my best.

**Pull request closed without merging**
