### PR TITLE
Fix constant of TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA

### LINKED ISSUE #144: Incorrect constant for TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
Credit to @ic0ns @pfg666 and @jurajsomorovsky for this report, thank you!

----

Should be 0xC014 instead of 0x0035

### PR DESCRIPTION
**Pull request by daenney**
We got the constant wrong, for some reason it was the constant of TLS_RSA_WITH_AES_256_CBC_SHA.

Fixes #144

### CODE REVIEW

**Comment by daenney** [comment]
The commit linter is wrong:
```
Fix constant of TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA

We got the constant wrong, for some reason it was the constant of

TLS_RSA_WITH_AES_256_CBC_SHA.

Fixes #144

-------------------------------------------------

The preceding commit message is invalid

it failed 'Limit the subject line to 50 characters' of the following checks
```
Yet:
```python
>>> len('Fix constant of TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA')
50
```
It's exactly fifty. I'll reword it, but we need to take a look at those commit linters soon. They're being a bit overzealous.

**Comment by Sean-Der** [comment]
@daenney yea sorry about the linter :/

@hugo has been pushing to move over to AngularJS commit message format (and I agree!) will also let us generated changes logs.

**Comment by daenney** [comment]
I believe the AngularJS format is what's nowadays known as the Conventional Commits. If not though, I'd argue for https://www.conventionalcommits.org/.

**Comment by Sean-Der** [comment]
@daenney 👍 to Conventional Commits. Looks like it already has tooling for Go already! https://github.com/talos-systems/conform

I am all for throwing away any 'custom rules' we have. My goal is just for our git history to be usable. I don't care what format it is in.

 also thanks for grabbing the PR :) I will work on getting mine done today!

**Comment by daenney** [comment]
Heh, no worries. This was a super tiny fix :smile:.

**Pull request merged**
