### PR TITLE
add support for certificate chain

### PR DESCRIPTION
**Pull request by jkralik**
#### Description
This patch add support for parsing certificate chain.

#### Breaking changes:
* certificate, privateKey was replaced by certifciate (tls.Certificate)
* verifyPeerCertificates uses array of bytes for chain certificates
  instead of certificate(*x509.Certificate)

#### Tested
Handshake was tested against mbedtls (iotivity-lite).

### CODE REVIEW

**Comment by igolaizola** [comment]
@jkralik thanks for improving `verifyPeerCertificates`. I should have added certificate chain support on my first implementation... now looks much better!

**Comment by Sean-Der** [comment]
@jkralik A quick update, we are going to land this ASAP!

We are going to release a `/v2` but going to land some non-breaking changes first. I will take care of getting merged, since we broke it and you already did all the hard work :)

thanks for using pion/dtls, really happy to see people using it!

**Comment by jkralik** [comment]
> 
> 
> @jkralik A quick update, we are going to land this ASAP!
> 
> We are going to release a `/v2` but going to land some non-breaking changes first. I will take care of getting merged, since we broke it and you already did all the hard work :)
> 
> thanks for using pion/dtls, really happy to see people using it!

@Sean-Der Hi - I will update PR at Monday.

**Comment by Sean-Der** [comment]
> > @jkralik A quick update, we are going to land this ASAP!
> > We are going to release a `/v2` but going to land some non-breaking changes first. I will take care of getting merged, since we broke it and you already did all the hard work :)
> > thanks for using pion/dtls, really happy to see people using it!
> 
> @Sean-Der Hi - I will update PR at Monday.

No we can do that! I think we are going to cause more conflicts, so please don't spend anymore time on this. My goal is to get some other things merged, and then create a `/v2` in about two weeks (with this being the first thing we land)

**Comment by jkralik** [comment]
OK. Thx 👍

**Comment by Sean-Der** [comment]
Closing for #142 

Thank you so much and sorry for how long it took me :( my hope is in the next few days we will have a `v2`

**Pull request closed without merging**
