### PR TITLE
Pin e2e Dockerfile

### PR DESCRIPTION
**Pull request by Sean-Der**
Using debian base instead

### CODE REVIEW

**Review by daenney — APPROVED** [review]
Uhg why is software so terrible.

**Review by at-wat — COMMENTED** [review]
It's better to leave an issue to remind us to revert it or migrate to newer version of OpenSSL later.

**Comment by Sean-Der** [comment]
Found the root issue here https://github.com/openssl/openssl/issues/16707

**Comment by Sean-Der** [comment]
@at-wat done! I found the issue upstream and opened a PR.

**Pull request merged**
