### PR TITLE
Only use algorithms in CertificateRequest

### LINKED ISSUE #418: Signature algorithm used in CertificateVerify selects algorithm not listed in CertificateRequest message
This is a violation of the RFC -  https://datatracker.ietf.org/doc/html/rfc5246#section-7.4.8

      "The hash and signature algorithms used in the signature MUST be
      one of those present in the supported_signature_algorithms field
      of the CertificateRequest message"

### Your environment.
  - Version: verified problem in current code, last commit: 7d92e05b506557005042a79a3c62e17864afaa61
 
Server responds with a certificate request not containing SHA-256 listed as a signature hash algorithm
Client sends certificate verify response using SHA-256 as the hash algorithm

### What did you expect?
Client should have used one of the algorithms listed in the certificate request message

### What happened?
Connection failed - failed to verify certificate

I researched this and the root cause appears to be that in flight5handler.go it is using the local hash algorithms for selection, not those contained in the certificate request message.

https://github.com/pion/dtls/blob/fe3a675d7c926e91adc09540b4526236367f9e48/flight5handler.go#L178

The fix for this seems straightforward - we need to remember the hash algorithms listed in the certificate request message ( possibly in State ? )  and then use these in selection of the algorithm used to generate the CertificateVerify message.

### PR DESCRIPTION
**Pull request by mschexnaydre**
For RFC compliance only algorithms in the certificate request shall be used.

#### Description
We should only be using one of the signature algorithms specified in the CertificateRequest message when generating the CertificateVerify message. Prior to this fix SHA-256 was always being used.

This change stores the HASH algorithm from the CertificateRequest message in the State object so that we can reference these later when generating the CertificateVerify message.

Removed hard-coded usage of SHA-256 in generateCertificateVerify, now uses the Digest method of the passed in algorithm.

#### Reference issue
Fixes #418

### CODE REVIEW

**Comment by Sean-Der** [comment]
Great fix @mschexnaydre 

Do you think it would be possible to write a test that validates that this is respected? A test that would break (but now works) with this commit. You can use OpenSSL to test against Pion (examples in e2e directory)

**Comment by mschexnaydre** [comment]
> Great fix @mschexnaydre
> 
> Do you think it would be possible to write a test that validates that this is respected? A test that would break (but now works) with this commit. You can use OpenSSL to test against Pion (examples in e2e directory)

Sure - I will take a look at doing that so we can make sure it does not get broken again in the future.

**Comment by adriancable** [comment]
@mschexnaydre - I’d like to take on reviewing/merging this.

A couple of requests:

- you can remove AUTHORS.TXT from the commit - it’s generated automatically via a CI script
- could you please rebase your changes to crypto.go to the current head? Due to recent merge of a PR related to ED25519 that will need to be done manually
- could you kindly add a test case for your changes

With those things in place, I’m happy to merge this.

**Comment by mschexnaydre** [comment]
> @mschexnaydre - I’d like to take on reviewing/merging this.
> 
> A couple of requests:
> 
> * you can remove AUTHORS.TXT from the commit - it’s generated automatically via a CI script
> * could you please rebase your changes to crypto.go to the current head? Due to recent merge of a PR related to ED25519 that will need to be done manually
> * could you kindly add a test case for your changes
> 
> With those things in place, I’m happy to merge this.

@adriancable Hi Adrian, so sorry for the delay on this - just have been completely busy with work.  Will definitely update this and get it updated so we can have this fix upstreamed.  Thanks.

**Comment by mschex** [comment]
I am going to revisit this and get a unit test written - I would like to get this fix into the mainline code.

**Comment by mschex** [comment]
@hasheddan this still seems to be a bug,  my code needs to be updated and a unit test added.  Is this something that you would be willing to review ?  Thanks -- fix for this issue: https://github.com/pion/dtls/issues/418

I am not sure if @adriancable or @Sean-Der are active in this project any longer ?

Thanks

**Comment by hasheddan** [comment]
Happy to review! Thanks for opening this @mschexnaydre! In the mean time, would you like to fix the outstanding conflicts?

**Comment by mschex** [comment]
Yes - I will definitely do that.  I just have to get set up again, I think
I also need some permissions to the repo again to update the PR?

Thanks,

Mike

**Comment by hasheddan** [comment]
> I think I also need some permissions to the repo again to update the PR?

You should be able to update, though it looks like you are now using a different GitHub account -- if you don't have access to the old one, feel free to close and open a new PR if preferred :)

**Comment by mschexnaydre** [comment]
This is the correct account now :) - sorry about that.

**Comment by mschexnaydre** [comment]
resolved to conflicts - working on a unit test

**Comment by mschexnaydre** [comment]
going to open a new PR that is a cleaner, should have rebased :(

**Pull request closed without merging**
