### PR TITLE
Remove usage of x/xerrors

### PR DESCRIPTION
**Pull request by jech**
The pieces of x/xerrors that we use have been integrated into
stdlib in go-1.13, and we don't support any earlier versions.

Tested under go-1.18 and go-1.13.

### CODE REVIEW

**Comment by daenney** [comment]
This seems to have a conflict on go.mod that needs to be resolved first.

**Comment by daenney** [comment]
```
# github.com/pion/dtls/v2/pkg/crypto/signaturehash [github.com/pion/dtls/v2/pkg/crypto/signaturehash.test]
pkg/crypto/signaturehash/signaturehash_go113_test.go:38:31: undefined: errors
pkg/crypto/signaturehash/signaturehash_test.go:93:31: undefined: errors
```

**Comment by jech** [comment]
Grr, I ran `go test` rather than `go test ./...`.  Sorry for that.

**Review by daenney — APPROVED** [review]

**Comment by daenney** [comment]
Thanks for this!

**Pull request merged**
