### PR TITLE
Docs/example listen cast

### PR DESCRIPTION
**Pull request by vidavidorra**
#### Description

Add a comment about `dtls.Conn` cast in listen example.

### CODE REVIEW

**Comment by Sean-Der** [comment]
@vidavidorra mind adding the same to `listen-psk` then LGTM!

Thanks for making things easier for people in the future :)

**Comment by Sean-Der** [comment]
Don't worry about the linter for this commit. I will squash everything for you

**Comment by vidavidorra** [comment]
> Thanks for making things easier for people in the future :)

No worries, happy to help!

> Don't worry about the linter for this commit. I will squash everything for you

I think the problem is the git hooks not being set up. How are those supposed to be set up locally? I'm not familiar with this since I've always used npm packages like husky to handle hooks for me.

**Comment by Sean-Der** [comment]
Merged with d5cce09442d3c5db4a18e6e170de3c09f20508f2 fantastic work!

**Comment by Sean-Der** [comment]
If you run `.github/install-hooks.sh` it *should* set them up.

You can also see everything we do in the `.travis.yml`. I am gone for 8 hours (bed time for me) but excited to get more people involved :)

**Pull request closed without merging**
