### PR TITLE
Move MessageCertificate to pkg/protocol/handshake

### PR DESCRIPTION
**Pull request by Sean-Der**
This is just a start. Looking to get reviewer sign-off before doing
more.

Relates to #333

### CODE REVIEW

**Comment by Sean-Der** [comment]
Sorry for how big this PR is :( I don't see any other way to do it. What do you think of the package structure/layout/naming conventions?

If you are happy with this what is best for reviewing? Would you like more small commits, or one large commit?

**Comment by jkralik** [comment]
For me it is OK when it is large commit if you just move the code.

**Review by jkralik — APPROVED** [review]
Nice !

**Comment by Sean-Der** [comment]
Thanks @jkralik! I will just go full steam ahead on this.

I think in ~week you will be able to be back on master. Satisfying the interface will be the easy part, just so much to export to make it possible O_O

**Comment by Sean-Der** [comment]
@jkralik @daenney If you have 10 minutes would you mind looking through `pkg` and making sure the naming/organization choices I made were sane? https://github.com/pion/dtls/tree/master/pkg

The PR itself was just massive so I don't have much hope of review. I made no public API/Code changes so the impact should be 0!

**Pull request merged**
